import 'dart:typed_data'; // Added this import
import 'package:flutter/material.dart';
import 'package:printing/printing.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../../core/theme/app_theme.dart';

class ReportScreen extends StatelessWidget {
  final String caseId;
  const ReportScreen({super.key, required this.caseId});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Identification Report'),
        actions: [
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: () {},
          ),
          IconButton(
            icon: const Icon(Icons.download),
            onPressed: () {},
          ),
        ],
      ),
      body: PdfPreview(
        build: (format) => _generatePdf(format, caseId),
        allowPrinting: true,
        allowSharing: true,
        canChangePageFormat: false,
        initialPageFormat: PdfPageFormat.a4,
        pdfFileName: 'DentID_Report_$caseId.pdf',
        loadingWidget: const Center(child: CircularProgressIndicator(color: AppColors.primary)),
      ),
    );
  }

  // FIXED: Changed Future<List<uint8>> to Future<Uint8List>
  Future<Uint8List> _generatePdf(PdfPageFormat format, String caseId) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        header: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('DentID Forensic Report', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18, color: PdfColors.cyan)),
            pw.Text('CASE ID: $caseId', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
          ],
        ),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 1.0 * PdfPageFormat.cm),
          child: pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
        ),
        build: (context) => [
          pw.Header(level: 0, text: 'Case Details'),
          pw.TableHelper.fromTextArray(
            context: context,
            data: <List<String>>[
              <String>['Field', 'Information'],
              <String>['Incident Name', 'Operation Northern Star'],
              <String>['Location', 'Toronto, ON'],
              <String>['Date of Discovery', '24 Oct 2023'],
              <String>['Investigator', 'Det. Sarah Miller'],
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Header(level: 0, text: 'Match Confidence Summary'),
          pw.Bullet(text: 'Morphology Match: 98%'),
          pw.Bullet(text: 'Restoration Match: 92%'),
          pw.Bullet(text: 'Spatial Relationship: 95%'),
          pw.Bullet(text: 'Age Estimation Match: 88%'),
          pw.SizedBox(height: 20),
          pw.Header(level: 0, text: 'Odontologist Declaration'),
          pw.Paragraph(
            text: 'I, Dr. Emily Vance, certify that the post-mortem dental records for case $caseId show a consistent and positive match with the ante-mortem records of Robert J. Thompson. The number of concordant features and lack of unexplainable discrepancies support this identification as certain.',
          ),
          pw.SizedBox(height: 40),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  // FIXED: Moved border into pw.BoxDecoration
                  pw.Container(
                      width: 150,
                      decoration: const pw.BoxDecoration(
                          border: pw.Border(bottom: pw.BorderSide(width: 1))
                      )
                  ),
                  pw.Text('Signature'),
                ],
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Date: 25 Oct 2023'),
                  pw.Text('License: #DENT-99281'),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 20),
          // Cleaned up the footer note to standard text to avoid layout errors
          pw.Container(
            alignment: pw.Alignment.centerRight,
            child: pw.Text('This report was generated by DentID v1.0 and constitutes a formal identification record.', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
          ),
        ],
      ),
    );

    return pdf.save();
  }
}